### ISSUE TITLE
Group chats don't show up (Yosemite)

### ISSUE THREAD

**Issue by carbureted** [CamHenlin/iMessageWebClient#5]
Messages from contacts in group chats just show up with the rest of the messages from that contact.

For instance, if I have a private conversation with Alice and a group conversation with Alice and Bob, messages from Alice in the group conversation will show up in the private conversation with Alice. The group conversation doesn't seem to show up in the UI at all.

 Not sure if this is expected behavior or different on older versions of OS X? Let me know if there's anything that I can provide.

**Comment by CamHenlin** [comment]
Nice catch, working on a fix right now

**Comment by CamHenlin** [comment]
@carbureted this should be fixed in afddb645cf. Let me know if it works for you!

**Comment by carbureted** [comment]
Awesome! That gets rid of the messages showing up in private chats. I still don't see any group chats - is that intended to be supported?

**Comment by CamHenlin** [comment]
Hmm, group chats should be working. Do your group chats have titles or are you using the default names when you create them?

**Comment by carbureted** [comment]
Default names, no titles. 

For instance - Alice, Bob, +1(333) 333-3333

**Comment by CamHenlin** [comment]
Ahh, okay, I'll take a look at getting that working. I can confirm that named group chats do work though

**Comment by carbureted** [comment]
Much appreciated! Let me know if I can help.

**Comment by CamHenlin** [comment]
Okay, I spent a little bit more time looking in to this, and unfortunately it is going to be a little bit of work to get it set up and working. Additionally and more unfortunately, I won't have time for a two or three weeks to get to it, but I am going to lay out what needs to be done in case someone else wants to take a crack at it and submit a pull request: Basically the SQLite command in app.js line 236 needs to be updated to better identify the unnamed groups, and then the following set of conditionals needs to be updated to support however those items are grouped. Additionally, the module that iMessageWebClient uses to send iMessages, iMessageModule, needs a fix to support sending messages to these unnamed groups: https://github.com/CamHenlin/iMessageModule/issues/1 What needs to happen there is that, it needs a slight pause after typing in every contact name/email/phone number to detect that each is a valid iMessage account, and then it can type and send the message. Again the simple workaround is to name the group chat

**Comment by carbureted** [comment]
The next little while is pretty busy for me too, but I'll start poking around to see if I can't get this working.

Thanks!
